GitRepo:
  name: myGitRepo
  gitProvider: frankzhu2003Github
  path: frankzhu2003/pipelines_swampup2020
  branches:
    include: templates

artifactoryIntegration: etrainingArtifactory

Image:
  name: DockerAppImage
  sourceRepository: docker
  dockerImageName: etrainning.jfrog.io/docker/swampup_docker_app_demo
  autoPull: true

DockerBuild:
  name: bld_docker_app
  dockerImageName: etrainning.jfrog.io/docker/swampup_docker_app_demo
  dockerFileName: Dockerfile
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

Pipeline:
  name: docker-build-push

DockerPush:
  name: push_docker_app
  targetRepository: docker-local

BuildInfo:
  autoPublishBuildInfo: true
  name: myBuildInfo